apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
data:
  POSTGRES_DB: grocerydb
  POSTGRES_USER: postgres
  POSTGRES_HOST: postgres  # DB service name

---
apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
type: Opaque
data:
  POSTGRES_PASSWORD: c3VyaQ==  # "suri" ni base64 encode cheyyali
