apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:latest
          envFrom:
            - configMapRef:
                name: postgres-config
            - secretRef:
                name: postgres-secret
          ports:
            - containerPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: postgres  # The hostname your backend will use
spec:
  selector:
    app: postgres  # Matches the labels in your Deployment
  ports:
    - protocol: TCP
      port: 5432  # External Service port
      targetPort: 5432  # Internal container port
  clusterIP: None  # (Optional) Makes it a headless service for DNS resolution

